---
- name: Set facts if docker container
  ansible.builtin.set_fact:
     is_docker_guest: "{{ ansible_virtualization_role | default('host') == 'guest' and ansible_virtualization_type | default('none') == 'docker' }}"

- name: Configure postfix_debconf_selections
  ansible.builtin.debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ postfix_debconf_selections }}"

- name: Install postfix packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ postfix_install }}"

- name: Configure Postfix standard templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: "{{ item.mode }}"
  loop: "{{ postfix_standard_templates }}"
  notify:
    - Restart postfix

- name: Configure transport maps
  ansible.builtin.template:
    src: transport.j2
    dest: "{{ postfix_conf_dir }}/transport"
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: "0644"
  notify:
    - Postmap transport
    - Restart postfix

- name: Configure sasl username/password when defined
  ansible.builtin.template:
    src: sasl_passwd.j2
    dest: "{{ postfix_conf_dir }}/sasl_passwd"
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: 0600
  when: 
    - postfix_sasl_auth_enabled is defined
    - postfix_sasl_auth_enabled | bool
  no_log: true
  notify:
    - Postmap sasl_passwd
    - Restart postfix

- name: Create empty aliases file if we don't have aliases (because the config has an alias map entry)
  ansible.builtin.file:
    dest: "{{ postfix_conf_dir }}/aliases"
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: 0644
    state: touch
    modification_time: preserve
    access_time: preserve
  when: postfix_aliases is not defined or postfix_aliases | length == 0
  notify:
    - New aliases
    - Restart postfix

- name: Add aliases (if we have any)
  ansible.builtin.lineinfile:
    dest: "{{ postfix_conf_dir }}/aliases"
    regexp: '^{{ item.user }}:.*'
    line: '{{ item.user }}: {{ item.alias }}'
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_aliases }}"
  when: postfix_aliases is defined and postfix_aliases | length > 0
  notify:
    - New aliases
    - Restart postfix

- name: Configure virtual aliases
  ansible.builtin.lineinfile:
    dest: "{{ postfix_conf_dir }}/virtual"
    regexp: '^{{ item.virtual }}.*'
    line: '{{ item.virtual }} {{ item.alias }}'
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_virtual_aliases }}"
  when: postfix_virtual_aliases is defined and postfix_virtual_aliases | length > 0
  notify:
    - New virtual aliases
    - Restart postfix

- name: Configure sender canonical maps
  ansible.builtin.lineinfile:
    dest: "{{ postfix_conf_dir }}/sender_canonical_maps"
    regexp: '^{{ item.sender }}.*'
    line: '{{ item.sender }} {{ item.rewrite }}'
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_sender_canonical_maps }}"
  when: postfix_sender_canonical_maps is defined and postfix_sender_canonical_maps | length > 0
  notify:
    - Postmap sender_canonical_maps
    - Restart postfix

- name: Configure generic table
  ansible.builtin.lineinfile:
    dest: "{{ postfix_conf_dir }}/generic"
    regexp: '^{{ item.pattern }}.*'
    line: '{{ item.pattern }} {{ item.result }}'
    owner: "{{ postfix_user }}"
    group: "{{ postfix_group }}"
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_generic }}"
  when: postfix_generic is defined and postfix_generic | length > 0
  notify:
    - Postmap generic
    - Restart postfix

- name: start and enable service
  ansible.builtin.service:
    name: postfix
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - postfix
    - postfix-start-enable-service
