# handlers file for postfix
---
- name: Restart postfix
  ansible.builtin.command: /bin/true
  notify:
    - Remove PID
    - Restart service

- name: Remove PID
  ansible.builtin.file:
    path: "~postfix/pid/master.pid"
    state: absent
  when: is_docker_guest

- name: Restart service
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: New aliases
  ansible.builtin.command: newaliases

- name: New virtual aliases
  ansible.builtin.command: postmap /etc/postfix/virtual

- name: Postmap sasl_passwd
  ansible.builtin.command: postmap hash:/etc/postfix/sasl_passwd

- name: Postmap sender_canonical_maps
  ansible.builtin.command: postmap hash:/etc/postfix/sender_canonical_maps

- name: Postmap generic
  ansible.builtin.command: postmap hash:/etc/postfix/generic

- name: Postmap transport
  ansible.builtin.command: postmap /etc/postfix/transport
