# handlers file for postfix
---
- name: Restart postfix
  ansible.builtin.command: /bin/true
  notify:
    - Remove PID
    - Restart service

- name: Remove PID
  ansible.builtin.file:
    path: "~postfix/pid/master.pid"
    state: absent
  when: is_docker_guest

- name: Restart service
  ansible.builtin.service:
    name: postfix
    state: restarted
  when: service_default_state | default('started') == 'started'

- name: New aliases
  ansible.builtin.command: postalias {{ postfix_conf_dir }}/aliases

- name: New virtual aliases
  ansible.builtin.command: postmap {{ postfix_conf_dir }}/virtual

- name: Postmap sasl_passwd
  ansible.builtin.command: postmap hash:{{ postfix_conf_dir }}/sasl_passwd

- name: Postmap sender_canonical_maps
  ansible.builtin.command: postmap hash:{{ postfix_conf_dir }}/sender_canonical_maps

- name: Postmap generic
  ansible.builtin.command: postmap hash:{{ postfix_conf_dir }}/generic

- name: Postmap transport
  ansible.builtin.command: postmap hash:{{ postfix_conf_dir }}/transport
